config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

  root 'cocktails#index'

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create]
  end

  resources :doses, only: [:destroy]
  resources :ingredients, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true

  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
      if @cocktail.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to @cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <h1 class="text-center" >Choose a cocktail</h1>
      <% @cocktails.order(:name).each do |cocktail| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <div class="card-category"><strong><%= link_to cocktail.name.downcase.capitalize, cocktail_path(cocktail) %></strong></div>
            <div class="card-thumbnail">
              <% if cocktail.photo? %>
                <%= cl_image_tag cocktail.photo.path, width: 150, height: 150, crop: :fill, radius: "max" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="card">
          <h3 class="text-center"><%= link_to "Add a new cocktail", new_cocktail_path %></p></h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="card padded">
          <h3>Add a new cocktail</h3>
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 ">
        <div class="card">
          <h1><%= @cocktail.name %></h1>
          <hr>
          <h3>Recipe</h3>
          <ul class="list-unstyled text-center">
            <% @cocktail.doses.each do |dose| %>
              <li><%= dose.description %> <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %>   (<%= link_to "delete", dose_path(dose),
                method: :delete,
                data: { confirm: "Are you sure?" } %>)</li>
            <% end %>
          </ul>
          <div class="text-center">
            <% if @cocktail.photo? %>
              <%= cl_image_tag @cocktail.photo.path, width: 300, height: 300, crop: :fill, radius: "25:0" %>
            <% end %>
          </div>
        </div>
      </div>
        <div class="col-xs12 col-sm-4 col-sm-offset-1">
          <div class="card">
            <h3>Add a new dose</h3>
            <%= render "doses/form" %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/ingredients/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="card">
          <h1>See all cocktails containing:</h1>
          <h2 id="blue-font"> <%= @ingredient.name %></h2>
          <ul class="list-unstyled text-center" id="ingredient-list">
            <% @ingredient.cocktails.each do |cocktail| %>
              <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeriousCocktailsByPauline</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|PT+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
  <div class="navbar-wagon" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/dtizchk6e/image/upload/v1492788496/cocktails_d60qn7.jpg');">
    <h1 id="silent-link"> <i class="fa fa-glass" aria-hidden="true"></i>  <%= link_to "serious cocktails", root_path %> </h1>
    <%= link_to "Home", root_path, class: "navbar-wagon-link" %>
  </div>
    <%= yield %>
  <div class="footer">
    <ul class="list-unstyled">
      <li><%= link_to "Send us a message", "http://www.lewagon.org" %> </li>
      <li><%= link_to "FAQ", "https://lmgtfy.com/" %></li>
    </ul>
  </div>
  </body>
</html>